import './globals.css';
import type { Metadata } from 'next';
import { Dancing_Script } from 'next/font/google';

const Dancing_Script_init = Dancing_Script({ 
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-dancing-script',
  });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Dancing_Script_init.variable}>{children}</body>
    </html>
  );
}
